### ISSUE TITLE
What is the license of libjs?

### ISSUE THREAD

**Issue by soimsoim** [streamich/libjs#1]
Hi. ^-^)

I have a question about libjs.
What is the license of libjs?
Can I use this package for commercial use?

I saw this package is public on npm site. (https://www.npmjs.com/package/libjs)
In this case, can I use this as Public Domain?

Thanks.

**Comment by streamich** [comment]
Hi @soimsoim ^-^)

I have added the [LICENSE](https://github.com/streamich/libjs/blob/master/LICENSE), it is indeed in public domain.

Sorry, for late reply.
